# Generated by Django 5.0.3 on 2024-04-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_expense',
            name='type',
            field=models.CharField(default='Income', max_length=10),
        ),
    ]
