# Generated by Django 5.0.3 on 2024-04-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_add_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_expense',
            name='type',
            field=models.CharField(default='expense', max_length=10),
        ),
    ]
