# Generated by Django 5.0.3 on 2024-04-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_add_expense_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_expense',
            name='type',
        ),
    ]
